# -*- coding: utf-8 -*-
"""json_api_to_dict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19btg8oDkGW37emLZrYv7Yae8dDgTyvAz
"""

import json

def load_and_modify_json(file_path):
    try:
        with open(file_path, 'r') as f:
            loaded_dict = json.load(f)
    except Exception as e:
        print(f"Error loading JSON file: {e}")
        return {}

    modified_dict = {}
    for key, value in loaded_dict.items():
        # Ensure value is a string for concatenation
        value_str = str(value) if not isinstance(value, str) else value
        modified_value = f"{key} {value_str}"
        modified_dict[key] = modified_value

    return modified_dict