# -*- coding: utf-8 -*-
"""train_csv_loader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19btg8oDkGW37emLZrYv7Yae8dDgTyvAz
"""

from langchain.docstore.document import Document
import pandas as pd

def train_csv_loader(df):
  def store_columns_to_list_by_row(df, columns):
      combined_answers_list = []
      for index, row in df.iterrows():
          for column in columns:
            combined_answers_list.append(row[column])
      return combined_answers_list

  # -- answers
  columns_to_extract = ['답변_1', '답변_2','답변_3','답변_4', '답변_5']
  answers = store_columns_to_list_by_row(df, columns_to_extract)

  # ------------------- csv to docs -------------------------- #
  csv_docs = []
  for i in range(len(answers)):
    doc =  Document(page_content= answers[i], metadata={"source": "local"})
    csv_docs.append(doc)

  return csv_docs