# -*- coding: utf-8 -*-
"""doc_to_vector_db.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1agXl0MMM0GVyxHRUKURTsAEHafaSO9k2
"""

import pandas as pd
from itertools import product
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.text_splitter import RecursiveCharacterTextSplitter

# -- init splitter
text_splitter = RecursiveCharacterTextSplitter(chunk_size = 500,
chunk_overlap = 100,
length_function = len)

# -- defining the path
modelPath = "distiluse-base-multilingual-cased-v1" #jhgan/ko-sbert-nil
model_kwargs = {'device':'gpu'}
encode_kwargs = {'normalize_embeddings': True}

# -- define embeddings
ko = HuggingFaceEmbeddings(
    model_name=modelPath,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

# -- chunking
chunks = text_splitter.split_documents(data)

# -- saving in db
db = FAISS.from_documents(chunks, ko)